# Default values for app_helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

service:
  type: LoadBalancer
  port: 80


resources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 512Mi

persistence:
  size: 64Mi
