apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app_helm.fullname" . }}
  labels:
    {{- include "app_helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app_helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app_helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- include "app_helm.env_password" . | nindent 12 }}
            {{- include "app_helm.env_aboba" . | nindent 12 }}
