- name: Docker role
  tags: [docker]
  block:
    - name: Do apt update
      become: true
      ansible.builtin.apt:
        update_cache: true

    - name: Install python docker package
      become: true
      ansible.builtin.import_role:
        name: geerlingguy.pip
      vars:
        pip_install_packages:
          - name: docker

          # docker-compose v1 is required by ansible docker_compose module
          - name: docker-compose

    - name: Import role geerlingguy.docker
      become: true
      vars:
        docker_install_compose: false
        docker_install_compose_plugin: false
      ansible.builtin.import_role:
        name: geerlingguy.docker
