server:
  disable: true

positions:
  filename: /data/positions.yaml

clients:
  - url: http://loki:3100/api/prom/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
      - json:
          expressions:
            log:
            stream:
            attrs:
            tag: attrs.tag
            time: time
      - timestamp:
          source: time
          format: RFC3339Nano
      - regex:
          # elvish from https://gist.github.com/ruanbekker/c6fa9bc6882e6f324b4319c5e3622460
          expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
          source: "tag"
      - labels:
          tag:
          stream:
          image_name:
          container_name:
          image_id:
          container_id:
      - output:
          source: log
