on:
  pull_request:
    paths:
      - app_python/**
      - .github/workflows/python.yml
  push:
    branches:
      - master

name: app_python

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app_python
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: poetry

      - run: poetry install --no-interaction
      - name: Run tests
        run: poetry run python -m pytest
