on:
  pull_request:
    paths:
      - app_python/**
      - .github/workflows/python.yml
  push:
    branches:
      - master

name: app_python

defaults:
  run:
    working-directory: ./app_python

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: poetry

      - run: poetry install --no-interaction
      - name: Run tests
        run: poetry run python -m pytest

  container:
    name: Container
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: app_python
          file: app_python/Containerfile
          push: true
          tags: chermnyx/inno-devops-python:latest
          cache-from: type=registry,ref=chermnyx/inno-devops-python:buildcache
          cache-to: type=registry,ref=chermnyx/inno-devops-python:buildcache,mode=max

  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.8@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: app_python --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

  snyk-docker:
    runs-on: ubuntu-latest
    needs: [container]
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: chermnyx/inno-devops-python:latest
          args: --file=app_python/Containerfile --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
