on:
  pull_request:
    paths:
      - app_rust/**
      - .github/workflows/rust.yml
  push:
    branches:
      - master

name: app_rust

defaults:
  run:
    working-directory: ./app_rust

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy,rustfmt
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: app_rust -> target

      - name: rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --manifest-path app_rust/Cargo.toml -- --check

      - name: clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --manifest-path app_rust/Cargo.toml

      - name: Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --manifest-path app_rust/Cargo.toml

  container:
    name: Container
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: chermnyx/inno-devops-python
          tags: latest
          context: app_rust
          containerfiles: ./app_rust/Containerfile
          layers: true

      - name: Push the container
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
