on:
  pull_request:
    paths:
      - app_rust/**
      - .github/workflows/rust.yml
  push:
    branches:
      - master

name: app_rust

defaults:
  run:
    working-directory: ./app_rust

jobs:
  test:
    name: Rust project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy,rustfmt
      - uses: Swatinem/rust-cache@v2

      # Currently actions-rs/cargo does not support changing
      # working directory so we need to use this hack for
      # rocket to find its config
      - run: ln -s app_rust/Rocket.toml ./
        working-directory: .

      - name: rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --manifest-path app_rust/Cargo.toml -- --check

      - name: clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --manifest-path app_rust/Cargo.toml

      - name: Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --manifest-path app_rust/Cargo.toml
